# Generated by Django 5.1.6 on 2025-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_App', '0002_alter_operation_name_alter_operation_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
